import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MeetBit Sample Meeting Link Embed</title>
        <meta name="description" content="A sample NextJS application on how to embed MeetBit Meeting Links." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <h1>MeetBit Sample Meeting Link Embed</h1>
        <p>A sample NextJS application on how to embed MeetBit Meeting Links.</p>

        <div className={styles.grid}>
          <a
            href="/normal"
            className={styles.card}
          >
            <h2>
              Normal <span>-&gt;</span>
            </h2>
            <p>
              See a publicly available meeting link.
            </p>
          </a>

          <a
            href="/protected"
            className={styles.card}
          >
            <h2>
              Protected <span>-&gt;</span>
            </h2>
            <p>
              See a protected meeting link with autogenerated OTP.
            </p>
          </a>

          <a
            href="https://link.meetbit.io/guest-app-guide"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Guest App Guide <span>-&gt;</span>
            </h2>
            <p>
              Read our guide on using & customizing the Guest App.
            </p>
          </a>

          <a
            href="https://meetbit.stoplight.io/docs/meetbit-public-api/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Read our full API Documentation.
            </p>
          </a>

        </div>
      </main>
    </>
  )
}
