import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import qs from 'qs'

const inter = Inter({ subsets: ['latin'] })

export const getServerSideProps = async () => {

  /* RETRIEVE ACCESS TOKEN */
  const accessTokenData = await axios({
    url: `https://api.meetbit.io/auth/token`,
    method: 'post',
    headers: {
      'Content-type': `application/x-www-form-urlencoded`,
    },
    data: qs.stringify({
      client_id: process.env.CLIENT_ID,
      client_secret: process.env.CLIENT_SECRET,
      grant_type: 'refresh_token',
      refresh_token: process.env.REFRESH_TOKEN
    }),
  })
  const accessToken = accessTokenData.data.access_token

  /* GENERATE OTP */
  const otpData = await axios({
    url: `https://api.meetbit.io/public/meetingLinks/${process.env.NEXT_PUBLIC_PROTECTED_MEETING_LINK_ID}/otp`,
    method: `post`,
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': `application/json'`
    },
  })
  const otp = otpData.data.otp

  return {
    props: { otp }
  }
}

export default function Protected({ otp }) {
  return (
    <>
      <Head>
        <title>MeetBit Sample Meeting Link Embed</title>
        <meta name="description" content="A sample NextJS application on how to embed MeetBit Meeting Links." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <h1><a href='/'>&lt;- </a>A Protected Meeting Link</h1>
        <p className={styles.description}>A protected meeting link with autogenerated OTP.</p>

        <iframe className={styles.iframe} src={`https://demo.meetbit.io/meeting/${process.env.NEXT_PUBLIC_PROTECTED_MEETING_LINK_ID}?embed=true&otp=${otp}`} />

      </main>
    </>
  )
}
